[project]
name = "scqrnn"
version = "0.1.0"
description = "Sorting Composite Quantile Regression Neural Network (SCQRNN) implemented in PyTorch"
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "torch>=2.13.0",
    "torchpsort>=0.1.6",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
